#!/data/data/com.termux/files/usr/bin/bash


echo "🆃🅴🆁🅼🆄🆇-🆈🆃🅳™"
╔════════════════════════════════════════╗               
 ▀█▀ █▀▀ █▀█ █▀▄▀█ █░█ ▀▄▀ ▄▄ █▄█ ▀█▀ █▀▄
 ░█░ ██▄ █▀▄ █░▀░█ █▄█ █░█ ░░ ░█░ ░█░ █▄▀                                                                
╚════════════════════════════════════════╝
echo -e "\e[036m" "𝗦𝗲𝗹𝗲𝗰𝘁 𝗔 𝗙𝗼𝗿𝗺𝗮𝘁➳"
echo -e "\e[032m" "1. Music 𝗠𝗽𝟯♫"
echo -e "\e[032m" "2. Video 𝟯𝟲𝟬𝗽"
echo -e "\e[032m" "3. Video 𝟰𝟴𝟬𝗽"
echo -e "\e[032m" "4. Video 𝟳𝟮𝟬𝗽"
echo -e "\e[032m" "5. Video 𝟭𝟬𝟴𝟬𝗽"

command='-no-mtime -o /data/data/com.termux/files/home/storage/shared/Youtube/%(title)s.%(ext)s -f'
read option

if [ "$option" -eq "1" ]
then
    echo "$command 140" > ~/.config/youtube-dl/config
    youtube-dl $1

elif [ "$option" -eq "2" ]
then
    echo "$command \"best[height<=360]\"" > ~/.config/youtube-dl/config
    youtube-dl $1

elif [ "$option" -eq "3" ]
then
    echo "$command \"best[height<=480]\"" > ~/.config/youtube-dl/config
    youtube-dl $1

elif [ "$option" -eq "4" ]
then
    echo "$command \"best[height<=720]\"" > ~/.config/youtube-dl/config
    youtube-dl $1

elif [ "$option" -eq "5" ]
then
    echo "$command \"best[height<=1080]\"" > ~/.config/youtube-dl/config
    youtube-dl $1
fi
